image.low=src/img/map1_1920x1080.jpg
image.low.width=1920
image.low.height=1080

image.medium=src/img/map1_3840x2160.jpg
image.medium.width=3840
image.medium.height=2160

image.high=src/img/map1_7680x4320.jpg
image.high.width=7680
image.high.height=4320
