#Map LOD Paths
#Fri Feb 07 01:48:54 MSK 2025
LOD2.Path=/home/laptop/IdeaProjects/TherianClone/tiles/LOD2
LOD=Levels
LOD1.Height=5000
LOD0.Width=15000
LOD0.Height=10000
LOD2.Width=3750
LODCount=3
TileHeight=360
LOD0.Path=/home/laptop/IdeaProjects/TherianClone/tiles/LOD0
LOD1.Width=7500
LOD1.Path=/home/laptop/IdeaProjects/TherianClone/tiles/LOD1
TileWidth=640
Tile=Dimensions
LOD2.Height=2500
